var namelist = {
    //"Hong Kong":{"name":"香港"},
    "Hong Kong":"香港",
	"Macao":"澳门",
	"Taiwan":"台湾",
	"Korea":"韩国",
	"Japan":"日本",

	"Albania":"阿尔巴尼亚",
	"Bosnia and Herzegovina":"波黑",
	"Bulgaria":"保加利亚",
	"Denmark":"丹麦",
	"United Kingdom":"英国",
	"Iceland":"冰岛",
	"Serbia":"塞尔维亚",
	"Montenegro":"黑山",
	"Croatia":"克罗地亚",
	"Latvia":"拉脱维亚",
	"Liechtenstein":"列支敦士登",
	"Lithuania":"立陶宛",
	"Macedonia":"马其顿",
	"Norway":"挪威",
	"Poland":"波兰",
	"Maro Virginia":"罗马尼亚",
	"Sweden":"瑞典",
	"Switzerland":"瑞士",
	"Czech":"捷克",
	"Hungary":"匈牙利",

	"Andorra":"安道尔",
	"Belgium":"比利时",
	"Germany":"德国",
	"Estonia":"爱沙尼亚",
	"Finland":"芬兰",
	"France":"法国",
	"Greece":"希腊",
	"Ireland":"爱尔兰",
	"Italy":"意大利",
	"Luxembourg":"卢森堡",
	"Malta":"马耳他",
	"Monaco":"摩纳哥",
	"Netherlands":"荷兰",
	"Austria":"奥地利",
	"Portugal":"葡萄牙",
	"San Marino":"圣马力诺",
	"Slovakia":"斯洛伐克",
	"Slovenia":"斯洛文尼亚",
	"Spain":"西班牙",
	"Vatican":"梵蒂冈",
	"United States":"美国",
	"Canada":"加拿大",
	"Brazil":"巴西",
	"Argentina":"阿根廷",
	"Australia":"澳大利亚",
	"new Zealand":"新西兰",
	"Singapore":"新加坡",
	"Malaysia":"马来西亚",
	"Thailand":"泰国",
	"Indonesia":"印度尼西亚",
	"India":"印度"
};


